name: moltis
version: '0.1.0'
summary: Rust version of moltbot
description: |
  Moltis is a Rust implementation of moltbot, a multi-feature bot system.

base: core24
grade: stable
confinement: strict

architectures:
  - build-on: [amd64]
  - build-on: [arm64]

apps:
  moltis:
    command: bin/moltis
    plugs:
      - network
      - network-bind

parts:
  moltis:
    plugin: rust
    source: .
    rust-path: ["crates/cli"]
    build-packages:
      - pkg-config
      - libssl-dev
